### ISSUE TITLE
Getting "Error:  No such file or directory" after including codefence.

### ISSUE THREAD

**Issue by jan0sch** [octopress/codefence#9]
Hi,

I followed the installation instructions and included the gem in my `Gemfile` and added the line `- octopress-codefence` to the `gems:` part in `_config.yml`. But after running `bundle install` jekyll refuses to start:

````
% bundle exec jekyll s
Configuration file: /PATH/_config.yml
            Source: /PATH
       Destination: /PATH/_site
      Generating... 
jekyll 2.5.3 | Error:  No such file or directory
````

If I remove the gem everything works. But I would really like to have code highlighting. ;-)

````
% uname -a
FreeBSD thor.rostock.home 10.1-RELEASE-p10 FreeBSD 10.1-RELEASE-p10 #0: Wed May 13 06:54:13 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
% ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [amd64-freebsd10]
````

Any ideas?

**Comment by parkr** [comment]
Maybe it's Octopress Docs-related? https://github.com/octopress/codefence/blob/master/lib/octopress-codefence.rb#L115

Can you re-run Jekyll with `--trace` and see if you get a line number?

Jekyll has some code highlighting built in, remember. :)

**Comment by jan0sch** [comment]
Ok, here is the stracktrace:

````
/usr/local/lib/ruby/2.1/find.rb:42:in `block in find': No such file or directory (Errno::ENOENT)
        from /usr/local/lib/ruby/2.1/find.rb:42:in `collect!'
        from /usr/local/lib/ruby/2.1/find.rb:42:in `find'
        from /usr/local/lib/ruby/gems/2.1/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/cache.rb:41:in `each'
        from /usr/local/lib/ruby/gems/2.1/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/cache.rb:41:in `to_a'
        from /usr/local/lib/ruby/gems/2.1/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/cache.rb:41:in `clean'
        from /usr/local/lib/ruby/gems/2.1/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/hooks.rb:13:in `post_write'
        from /usr/local/lib/ruby/gems/2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:223:in `block in write'
        from /usr/local/lib/ruby/gems/2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `each'
        from /usr/local/lib/ruby/gems/2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `write'
        from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:53:in `process'
        from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
````

**Comment by imathis** [comment]
Thanks for posting the stack trace. I think this has something to do with the caching. I'll have a look.

**Comment by imathis** [comment]
I belive I've fixed this in version 4.2.5 of octopress-code-highlighter. If you update that gem, you should be good to go. Let me know if there's still any trouble.

**Comment by jan0sch** [comment]
No luck here. :cry: After running `bundle update` an `bundle exec jekyll s --trace` produces the following stacktrace:

````
/usr/local/lib/ruby/2.1/find.rb:42:in `block in find': No such file or directory (Errno::ENOENT)
	from /usr/local/lib/ruby/2.1/find.rb:42:in `collect!'
	from /usr/local/lib/ruby/2.1/find.rb:42:in `find'
	from /usr/local/lib/ruby/gems/2.1/gems/octopress-code-highlighter-4.2.5/lib/octopress-code-highlighter/cache.rb:43:in `each'
	from /usr/local/lib/ruby/gems/2.1/gems/octopress-code-highlighter-4.2.5/lib/octopress-code-highlighter/cache.rb:43:in `clean'
	from /usr/local/lib/ruby/gems/2.1/gems/octopress-code-highlighter-4.2.5/lib/octopress-code-highlighter/hooks.rb:13:in `post_write'
	from /usr/local/lib/ruby/gems/2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:223:in `block in write'
	from /usr/local/lib/ruby/gems/2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `each'
	from /usr/local/lib/ruby/gems/2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `write'
	from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:53:in `process'
	from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.1/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
````

**Comment by parkr** [comment]
https://github.com/octopress/code-highlighter/blob/master/lib/octopress-code-highlighter/cache.rb#L43 should just do an `exist?` check :)

**Comment by imathis** [comment]
Grr. I guess I mistakenly expected Find to handle the enumerator that it returns properly. I'll add an `exists?`check. Like an animal.

**Comment by imathis** [comment]
Ok, update again. This should work. Sorry for the runaround.

**Comment by jan0sch** [comment]
Works like a charm. Thanks for the fast fix.

The new octopress rocks by the way. :+1:

**Comment by imathis** [comment]
Sweet. Thanks! :zap: :guitar: :zap:
